import turtle as turt


turt.fillcolor("black")
turt.begin_fill()
turt.circle(5)
turt.end_fill()
turt.goto(0,0)
turt.right(45)
turt.forward(141.421)

turt.fillcolor("black")
turt.begin_fill()
turt.circle(5)
turt.end_fill()
turt.left(135)
turt.forward(200)

turt.fillcolor("black")
turt.begin_fill()
turt.circle(5)
turt.end_fill()
turt.left(90)
turt.forward(20)
turt.penup()
turt.forward(20)
turt.pendown()
turt.forward(40)
turt.penup()
turt.forward(20)
turt.pendown()
turt.forward(40)
turt.penup()
turt.forward(20)
turt.pendown()
turt.forward(40)
turt.fillcolor("black")
turt.begin_fill()
turt.circle(5)
turt.end_fill()

turt.left(90)
turt.forward(200)

turt.fillcolor("black")
turt.begin_fill()
turt.circle(5)
turt.end_fill()
turt.left(90)
turt.forward(20)
turt.penup()
turt.forward(20)
turt.pendown()
turt.forward(40)
turt.penup()
turt.forward(20)
turt.pendown()
turt.forward(40)
turt.penup()
turt.forward(20)
turt.pendown()
turt.forward(40)

turt.penup()
turt.goto(0,0)
turt.left(45)
turt.pendown()
turt.forward(141.421)

turt.penup()
turt.goto(0,0)
turt.left(90)
turt.pendown()
turt.forward(141.421)

turt.penup()
turt.goto(0,0)
turt.left(90)
turt.pendown()
turt.forward(141.421)



